For check date.py
Gaydarenko/PY200 pull request #1
Opened 2020-09-17 06:42 UTC by Gaydarenko

2020-09-17 07:51 UTC, EnotYoyo requested changes
И проверьте работоспособность функций прибавления дат: add_month периодически падает с ValueError (данные подаю корректные)

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        return True if year % 4 == 0 and year % 100 != 0 else False
Забыли про делимость на 400. По моим тестам ровно они провалились. Эти даты валидны: 1200.2.29, 800.2.29

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        if month == 2:
Проверка понятна, но так будет короче:
```python
return cls.DAY_OF_MONTH[cls.is_leap_year(year)][month - 1]
```

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        # if not isinstance(args[0], int):
А почему эти проверки закомментированы?

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        args = value.split('.')
Надо бы проверить, что value - str

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        return self._date
А смысл это сохранять? Можно генерировать "на лету": `return f"{self.year}.{self.month}.{self.day}"`

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        self._date = '.'.join(list(map(str, (self.day, self.month, self.year))))
Это к вопросу выше. Смысл хранить отдельно в строковом формате дату не имеет смысла

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        self.year += year
Забыли про один важный момент: если был высокосный код, 29 февраля, а потом произошел переход на невысокосный год - дата станет невалидной.

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        # self.__is_valid_date(value, self.month, self.day)
Лучше проверять всю тройку из-за переключения между высокосными и невысокосными годами

2020-09-17 07:51 UTC, EnotYoyo commented on Date.py
> +        # self.__is_valid_date(self.year, value, self.day)
Лучше проверять всю тройку из-за переключения между месяцами с разным кол-вом максимальных дней.

2020-09-17 11:55 UTC, Gaydarenko commented on Date.py
> +        if month == 2:
Это был осмысленный выбор. Идея была сократить время - по возможности не вызывать is_leap_year.

2020-09-17 12:22 UTC, Gaydarenko commented on Date.py
> +        args = value.split('.')
Fixed

2020-09-17 12:33 UTC, Gaydarenko commented on Date.py
> +        return self._date
Возможно я что-то не так понял.
в шаблоне у нас были даны @property от date и @date.setter от date.  
@property нам только возвращает что-то
@date.setter реализованы проверки на то что value - строка, которую можно разбить на три части

именно строкой я подаю только сюда

2020-09-17 12:39 UTC, Gaydarenko commented on Date.py
> +        self._date = '.'.join(list(map(str, (self.day, self.month, self.year))))
fixed

2020-09-17 12:41 UTC, EnotYoyo commented on Date.py
> +        return self._date
Кажется пока писал пример Вы поправили комментарий :) 
Но на всякий случай все равно оставлю. У Вас была возможна такая ситуация:
```python
d = Date(884, 7, 17)
d.date = "885.1.1"
d.day = 31
print(d.date)  # 1.1.885, а должно быть 31.1.885
```

2020-09-17 13:24 UTC, Gaydarenko commented on Date.py
> +        return True if year % 4 == 0 and year % 100 != 0 else False
fixed

2020-09-17 13:38 UTC, Gaydarenko commented on Date.py
> +        # if not isinstance(args[0], int):
fixed

2020-09-17 13:54 UTC, Gaydarenko commented on Date.py
> +        # self.__is_valid_date(value, self.month, self.day)
не понимаю как - выдает ошибку, мол self.month еще не определен

2020-09-17 13:55 UTC, Gaydarenko commented on Date.py
> +        # self.__is_valid_date(self.year, value, self.day)
не понимаю как - выдает ошибку, мол self.yearh еще не определен

2020-09-17 14:02 UTC, Gaydarenko commented on Date.py
> +        self.year += year
fixed

2020-09-17 14:04 UTC, EnotYoyo commented on Date.py
> +        # self.__is_valid_date(self.year, value, self.day)
В init-e вызовите один раз `__is_valid_date`, а потом сохраняйте сразу в скрытые атрибуты:
```python
    def __init__(self, *args):
        self.__is_valid_date(*args)
        self._year = args[0]
        self._month = args[1]
        self._day = args[2]
```
Только __is_valid_date должен проводить все проверки (число и типы аргументов, корректность даты)

2020-09-17 14:53 UTC, Gaydarenko commented on Date.py
> +        # self.__is_valid_date(self.year, value, self.day)
Теперь другая проблема: раньше в методе add_day я использовал команду self.day += days.
При этом вызывалось свойство day (а оно, в свою очередь, вызывало setter)  и производилась передача значений в __is_valid_date для проверки корректности значения day.

Сейчас проверка не вызывается и у меня получаются дни более 31

2020-09-17 14:54 UTC, Gaydarenko commented on Date.py
> +        # self.__is_valid_date(self.year, value, self.day)
стр.132-142

2020-09-21 20:04 UTC, EnotYoyo requested changes

2020-09-21 20:04 UTC, EnotYoyo commented on Date.py
> +            self.month = remain % 12
Вылитает на этой строчке в следующем примере: 
```python
d = Date(1473, 11, 21)
d.add_month(73)
```

2020-09-21 20:23 UTC, EnotYoyo commented on Date.py
> +        date2_ = date2.split('.')
Если подать на вход не строчку, то вылетит исключение еще на этом месте. Я бы сделал по-другому:
- Добавил бы classmethod, который создает Ваш Date из строки: `Date.from_string(date1)` или можно научить класс обрабатывать ситуацию `Date("2020.10.09")`
- Создать два новых экземпляра Date из параметров, которые передаются на вход методу date2_date1. 
- Дальше по коду работать и этими экземплярами (то есть с атрибутами, а не создавать переменные) 

Так код будет выглядеть аккуратнее, а все проверки валидности будут проходить на моменте создания экзепляров класса.

2020-09-22 11:13 UTC, Gaydarenko commented on Date.py
> +            self.month = remain % 12
Fixed

2020-09-22 12:47 UTC, EnotYoyo commented
Где-то еще есть ошибка: 
```python 
d = Date(553, 10, 15)
d.add_month(79)  # 553.5.15, почему-то год не поменялся
```

2020-09-22 20:31 UTC, EnotYoyo commented
Всё ещё нет :( 
```python 
d = Date(838, 3, 31)
d.add_month(49)
```

2020-09-23 18:35 UTC, Gaydarenko commented on Date.py
> +        date2_ = date2.split('.')
на вход подаю экземпляры класса

2020-09-23 20:43 UTC, EnotYoyo commented
И новый вариант ошибки: 
```python 
d = Date(580, 2, 29)
d.add_month(86) 
```

2020-09-24 10:20 UTC, Gaydarenko commented
Ааааааааааааааа! Да как так то??
Вроде все проверил.

2020-09-24 11:25 UTC, EnotYoyo commented
Тесты пройдены, задание засчитано, поздравляю :)

2020-09-24 11:25 UTC, EnotYoyo approved these changes

2020-09-24 11:33 UTC, merged