For check linked list
Gaydarenko/PY200 pull request #2
Opened 2020-09-18 17:52 UTC by Gaydarenko

Я еще не доделал. Но у меня получилось сдвинуться с мертвой точки (было критичное непонимание).

2020-09-18 18:34 UTC, EnotYoyo commented on linkedlist.py
> +    # def __reversed__(self):
А что не так с методом?

2020-09-18 18:34 UTC, EnotYoyo commented on linkedlist.py
> +        index = -1
Используйтке enumerate, так код будет чище :)

2020-09-18 18:39 UTC, EnotYoyo commented
> было критичное непонимание

А что именно было непонятно? 

Пока что все очень хорошо. Единственное - можете сделать дополнительный метод, который будет возвращать итератор по нодам (аналогия __iter__ только которые возвращает сами ноды, а не данные). Это позволит не писать for через длину списка.

2020-09-18 19:16 UTC, Gaydarenko commented on linkedlist.py
> +    # def __reversed__(self):
Пока не понял что этот метод должен делать. Начал делать под одно действие, потом увидел, что возможно нужно совершенно другое. 
И переключился пока на другие методы

2020-09-21 13:01 UTC, Gaydarenko commented on linkedlist.py
> +        index = -1
fixed

2020-09-24 11:41 UTC, EnotYoyo requested changes

2020-09-24 11:41 UTC, EnotYoyo commented on linkedlist.py
> +            self.__tail = self.__tail.prev
А у нового tail все еще останется ссылка next

2020-09-24 11:41 UTC, EnotYoyo commented on linkedlist.py
> +            self.__head = self.__head.next
А занулить у нового head prev? Тут спасает то, что prev это weakref, но лучше явно занулить

2020-09-24 11:41 UTC, EnotYoyo commented on linkedlist.py
> +    def find(self, node: Node) -> int:
зачем тут нужен именно Node? Ищите сразу по данным.

2020-09-24 11:41 UTC, EnotYoyo commented on linkedlist.py
> +    def remove(self, node: Node):
Аналогично, ищите по данным. И у Вас описание из документации не соответствует тому, что делает функция (докстринг говорит, что удаляется первая нода с такими данными, а на самом деле это не так, поскольку вы проверяете отдельно tail)

2020-09-24 16:56 UTC, Gaydarenko commented on linkedlist.py
> +            self.__head = self.__head.next
Изначально так и задумывалось - понятный и привычный путь. Но как раз по вашему совету попробовал в коде использовать weakref. Переработал и другие части, чтобы убрать избыточность.  И это было моей небольшой гордостью, что понял и сумел применить.
Хочется понять эту грань где избыточность. Почему лучше явно занулить?  Это для удобства чтения кода или возможности других багов, про которые я пока не знаю?

2020-09-24 16:57 UTC, Gaydarenko commented on linkedlist.py
> +            self.__tail = self.__tail.prev
fix

2020-09-24 17:02 UTC, Gaydarenko commented on linkedlist.py
> +    def find(self, node: Node) -> int:
В некоторых функциях указана переменная на входе "value", а у некоторых "node". Предположил, что речь идет о подаче на вход именно ноды. К тому же было интересно попробовать использовать ноду (чтобы перестать их опасаться).

2020-09-24 17:13 UTC, Gaydarenko commented on linkedlist.py
> +    def remove(self, node: Node):
fix

2020-09-24 19:22 UTC, EnotYoyo commented on linkedlist.py
> +            self.__head = self.__head.next
Это здорово, что Вы здесь сделали это осознано. Занулять стоит, поскольку это корректно с точки зрения логики. Конкретно этот класс не управляет сборщиком мусора, Вы не можете быть уверен, что пользователь Вашего класса [не выключил](https://docs.python.org/3/library/gc.html#gc.disable) сборщик мусора в своей программе.

2020-09-24 19:27 UTC, EnotYoyo commented
Поправьте зануление и зачтено :+1:

2020-09-24 19:28 UTC, EnotYoyo approved these changes

2020-09-25 18:54 UTC, merged